### ISSUE TITLE
Node Type Error

### ISSUE THREAD

**Issue by RichardWeng001** [RichardWeng001/Houdini-Interpreter#7]
Source:

Traceback (most recent call last):
  File "json_interpreter", line 44, in <module>
  File "C:/PROGRA\~1/SIDEEF\~1/HOUDIN\~1.383/houdini/python3.7libs\houpythonportion\ui.py", line 1081, in decorator
    return func(*args, **kwargs)
  File "C:/PROGRA\~1/SIDEEF\~1/HOUDIN\~1.383/houdini/python3.7libs\hou.py", line 14148, in createNode
    return _hou.Node_createNode(self, node_type_name, node_name, run_init_scripts, load_contents, exact_type_name, force_valid_node_name)
hou.OperationFailed: The attempted operation failed.
Invalid node type name

**Comment by RichardWeng001** [comment]
A error with `par_node`, temporarily fixed.
